---
title: "Lung Cancer Bayes Net Notes"
author: "Piotr Mankowski"
date: "March 10, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# General Ideas about use of BN
We want to represent the diagnosis and treatment knowledgebase as a BN

For a given patient, we will have given diagnostic information, demographic information, tumor genotype information, etc.

## Medical Diagnosis
- primary tumor size
- primary tumor location
- invasive properties

## Tumor Genetics and Biomarkers
- genetic subtype
- presence of different cell surface receptors
- expression info from stroma (classified --> outcome?)


## Metastasis Info (how to model multiple metastatic locations?)
- # of metastasis
- location
- size?

## Patient Demographics
- age
- sex
- ethnicity
- height
- weight

## Patient Health Metrics
- Blood pressure + other vital signs
- Overall health assessment?

## Treatment Options
- Chemo
- Surgical
- Radiology
- other?

## Outcome Variables
- Quality of Life
- Prognosis (remission vs. recurrance)


The results of putting in known info/ selecting type of treatment etc. on q of life and prognosis could be informative for decision-making.

(read more about infrerence with BN)

## Possible Datasets

### Wisconsin Data

There are three datasets in this group. They all contain cell nucleous features and an outcome. The first two use malignant/benign outcomes, while the 3rd has recurrance/no recurrance

It might be possible to build a very simple BN with the outcomes as the variable. Could be opportunities for determining BN strucutre from data, or for making a BN where the 
cell strucutres have some arbitrary relationship. For example, Bland Chromatin --> Mitoses, and Mitoses --> class. 

For the other two datasets, you could relate areas and permiters and other things together, and make some unfounded BN

### UCI Data:

A possible BN could include age --> menopause, 

menopause -> tumorsize/degmal

inv-nodes --> node caps

node-caps --> 

size/degree --> inv-nodes 


degree/size/inv-nodes/node-caps --> irradiation

irradiation/size/deg/node-caps --> recurrance


